spring:
  application:
    name: Shop

  datasource:
    url: jdbc:postgresql://localhost:5432/Shop
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    schema: public

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        globally_quoted_identifiers: true